-- Create database if not exists
CREATE
DATABASE IF NOT EXISTS rivulet_db;

USE
rivulet_db;

CREATE TABLE shipments
(
  carrier_code                     VARCHAR(50)  NOT NULL,
  tracking_number                  VARCHAR(255) NOT NULL,
  org_id                           VARCHAR(50)  NOT NULL,
  tracking_qualifier               VARCHAR(100) NOT NULL,
  shipment_source                  VARCHAR(100),
  package_weight                   DECIMAL(10, 2),
  package_weight_unit              VARCHAR(50),
  carrier_promise_date             DATETIME,
  origin_city                      VARCHAR(255),
  origin_state                     VARCHAR(255),
  origin_postal_code               VARCHAR(50),
  origin_country                   VARCHAR(50),
  shipment_status_name             VARCHAR(255),
  shipment_status_code             VARCHAR(255),
  destination_city                 VARCHAR(255),
  destination_state                VARCHAR(255),
  destination_postal_code          VARCHAR(50),
  destination_country              VARCHAR(50),
  is_return                        BOOL         NOT NULL,
  merchant_order_id                VARCHAR(255),
  origin_address_line_1            VARCHAR(255),
  origin_address_line_2            VARCHAR(255),
  destination_address_line_1       VARCHAR(255),
  destination_address_line_2       VARCHAR(255),
  ship_date                        DATETIME,
  shipper_reference                VARCHAR(255),
  specific_location_code           VARCHAR(100),
  facility_type_code               VARCHAR(100),
  delivery_location                VARCHAR(255),
  invoice_number                   VARCHAR(255),
  no_of_packages                   INT,
  recipient_company                VARCHAR(255),
  recipient_contact_name           VARCHAR(255),
  shipper_company                  VARCHAR(255),
  shipper_name                     VARCHAR(255),
  special_handling                 VARCHAR(255),
  tendered                         DATETIME,
  service_type_code                VARCHAR(255),
  service_type_name                VARCHAR(255),
  update_reason                    VARCHAR(255),
  mps_role                         VARCHAR(255),
  mps_relationship_type            VARCHAR(255),
  mps_tracking_number              VARCHAR(255),
  mps_carrier_code                 VARCHAR(255),
  shipper_account_number           VARCHAR(255),
  bill_to_internal                 VARCHAR(255),
  bill_to_account_number           VARCHAR(255),
  recipient_account_number         VARCHAR(255),
  partner_carrier_tracking_number  VARCHAR(255),
  classification                   VARCHAR(255),
  movement_status_code             VARCHAR(255),
  delivery_date                    DATETIME,
  risk_score                       DECIMAL(10, 2),
  estimated_date                   DATETIME,
  estimated_date_tw_begin          DATETIME,
  estimated_date_tw_end            DATETIME,
  gddp_risk_score                  DECIMAL(10, 2),
  arrival_status_code              VARCHAR(50),
  delivery_prediction              VARCHAR(255),
  proof_of_delivery                TEXT,
  received_by                      VARCHAR(255),
  delivered_to                     VARCHAR(255),
  actual_delivery_city             VARCHAR(255),
  actual_delivery_state            VARCHAR(255),
  actual_delivery_postal_code      VARCHAR(255),
  actual_delivery_country          VARCHAR(255),
  actual_delivery_address_line_1   VARCHAR(255),
  actual_delivery_address_line_2   VARCHAR(255),
  actual_delivery_gpspodcoordinate VARCHAR(255),
  no_of_attempted_deliveries       INT,
  signature_available              VARCHAR(255),
  created_date                     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_modified_date               DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (carrier_code, tracking_number, org_id, tracking_qualifier)
);

CREATE TABLE shipment_events
(
  carrier_code       VARCHAR(50)  NOT NULL,
  tracking_number    VARCHAR(255) NOT NULL,
  org_id             VARCHAR(50)  NOT NULL,
  tracking_qualifier VARCHAR(50)  NOT NULL DEFAULT '',
  status             VARCHAR(50)  NOT NULL,
  status_detail      VARCHAR(255),
  raw_carrier_code   VARCHAR(50),
  message            VARCHAR(255),
  event_date         DATETIME     NOT NULL,
  event_code         VARCHAR(5),
  scannedat          DATETIME,
  event_reason_code  VARCHAR(20),
  sub_status         TEXT,
  status_code        VARCHAR(50),
  city               VARCHAR(255),
  state              VARCHAR(255),
  country            VARCHAR(50),
  postal_code        VARCHAR(50),
  gpspodcoordinate   VARCHAR(255),
  address_line_1     VARCHAR(255),
  address_line_2     VARCHAR(255),
  created_date       DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (carrier_code, tracking_number, org_id, tracking_qualifier, status, event_date),
  SHARD KEY(carrier_code,tracking_number,org_id,tracking_qualifier)
);

CREATE TABLE shipment_event_summary
(
  carrier_code    VARCHAR(50),
  tracking_number VARCHAR(255),
  event_time      DATETIME,
  event_type      VARCHAR(100),
  facility_id     VARCHAR(50),
  weight          DECIMAL(10, 2),
  PRIMARY KEY (carrier_code, tracking_number, event_time)
    SHARD KEY (carrier_code, tracking_number)
);
